# Generated by Django 6.0.4 on 2026-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='guarantee_percentage',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='offers_guarantee',
            field=models.BooleanField(default=False),
        ),
    ]
